function(Clang_GetStyle_CXX IS_CLANG_GCC IS_CLANG_MSVC)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            set(${IS_CLANG_GCC} OFF PARENT_SCOPE)
            set(${IS_CLANG_MSVC} ON PARENT_SCOPE)
        elseif (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
            set(${IS_CLANG_GCC} ON PARENT_SCOPE)
            set(${IS_CLANG_MSVC} OFF PARENT_SCOPE)
        else()
            set(${IS_CLANG_GCC} OFF PARENT_SCOPE)
            set(${IS_CLANG_MSVC} OFF PARENT_SCOPE)
        endif()
    else()
        set(${IS_CLANG_GCC} OFF PARENT_SCOPE)
        set(${IS_CLANG_MSVC} OFF PARENT_SCOPE)
    endif()
endfunction()
